import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { Container } from 'react-bootstrap'
import HomeScreen from './HomeScreen'
// import { BrowserRouter as Router, Route } from 'react-router-dom'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sequoia shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/sequoia-tree.ico" />
      </Head>
      <Header/>
      <main className="py-3">
        <Container>
          <HomeScreen/>
        </Container>

      </main>

      <Footer/>
    </div>
  )
}
